### ISSUE TITLE
Cannot read text from .xls file

### ISSUE THREAD

**Issue by andreas-eriksson** [Sicos1977/IFilterTextReader#19]
Hi, I get the following error when I try to read text from an old excel file (.xls).

   at IFilterTextReader.NativeMethods.IPersistStream.Load(IStream pStm)
   at IFilterTextReader.FilterLoader.LoadAndInitIFilter(Stream stream, String extension, Boolean disableEmbeddedContent, String fileName, Boolean readIntoMemory) in C:\Git\IFilterTextReader\IFilterTextReader\FilterLoader.cs:line 160
   at IFilterTextReader.FilterReader..ctor(String fileName, String extension, Boolean disableEmbeddedContent, Boolean includeProperties, Boolean readIntoMemory, FilterReaderTimeout filterReaderTimeout, Int32 timeout) in C:\Git\IFilterTextReader\IFilterTextReader\FilterReader.cs:line 201
   at IFilterTextViewer.MainForm.SelectButton_Click(Object sender, EventArgs e) in C:\Git\IFilterTextReader\IFilterTextViewer\MainForm.cs:line 139
Exception from HRESULT: 0x8004170C

Is there anything I can do to make it work?

**Comment by Sicos1977** [comment]
I saw that you fixed it yourself 👍 ... can you tell me what the problem was?

Greetings,
Kees van Spelde

**Comment by Sicos1977** [comment]
I published a new version (1.5.3) to nuget.

**Comment by andreas-eriksson** [comment]
I'm not sure why the error occurs. Some suggestions seem to indicate that installed filters could be corrupt but it happens on my test machine as well.

I am hoping that the fix will make the code work for a few more legacy formats.

Thanks :)

**Comment by Sicos1977** [comment]
Is it possible to send me the old xls file so that I can investigate it some more? If so then send it to sicos2002@hotmail.com

Also if you want to do really advanced things with extracting data from files then have a look at Tika (https://tika.apache.org/). There is also a .NET port that is generated with IKVM (https://github.com/KevM/tikaondotnet).... it's not that iFilters aren't good but there is a wider support for files in Tika.

**Comment by andreas-eriksson** [comment]
Mail sent.

Thanks for the info, I will definitely investigate Tika.

**Comment by Sicos1977** [comment]
Also just to to satisfy my own curiosity... for what are you using my library?

**Comment by andreas-eriksson** [comment]
It's used to extract text from documents and then making them searchable with Lucene.

**Comment by Sicos1977** [comment]
Also another thing, you also can use the Java Tika version. It has a web interface that can be called from .NET. It's just what you prefer. I myself prefer .NET above Java.

**Comment by andreas-eriksson** [comment]
Me too.

Tika sure looks interesting, especially since it doesn't seem to have any other dependencies. Would be nice if users didn't have to install Office.

**Comment by Sicos1977** [comment]
You also don't have to install office for my iFilter library. There is a iFilter package for it. You can find it overhere --> https://www.microsoft.com/en-us/download/details.aspx?id=17062

**Comment by Sicos1977** [comment]
I also made an MSGReader library to extract information from MSG files. It has no Ifilter support since that is kind of difficult to make in .NET. But with some coding you probably can make it work. You can find it overhere --> https://github.com/Sicos1977/MSGReader. Other "extracting" libraries can be found overhere --> https://github.com/Sicos1977/OfficeExtractor and https://github.com/Sicos1977/VCardReader
